imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:
        default_locale: %locale%
        lifetime:       900
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

services:
    #para saber que usuario se conecta y se desconecta
    authentication_handler:
        class: mio\mioBundle\AuthenticationHandler
        arguments: [@router , @doctrine.orm.entity_manager, @security.context]
    #para ver los cambios en las entidades
    listenercrud:
        class: mio\mioBundle\ListenerCrud
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: onFlush}
    #para personalizar la pagina de accesso denegado
    accessdenied_handler:
        class: mio\mioBundle\AccessDeniedHandler
        arguments: [@router , @security.context ]
        tags:
           - { name: kernel.event_listener, event: security.kernel_response, method: handle}
    #para personalizar la pagina de ruta no encontrada
    listenerexepcion:
       class: mio\mioBundle\ListenerExcepcion
       arguments: [@router]
       tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    listenerparalogout:
        class: mio\mioBundle\RequestListener
        arguments: [@router, @security.context]
        tags:
           - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }